# Generated by Django 6.0.6 on 2026-07-10 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0002_rename_date_submitted_anonymouscomplaint_submitted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
